# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
steps:

- task: DownloadSecureFile@1
  name: publicKey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'azure-resource-manager-service-connection'
    azureResourceGroup: 'kubernetes_prod'
    kubernetesCluster: 'k8_prod'
    namespace: 'default'
    command: 'repo'
    arguments: 'add prometheus-community https://prometheus-community.github.io/helm-charts'
    
- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'azure-resource-manager-service-connection'
    azureResourceGroup: 'kubernetes_prod'
    kubernetesCluster: 'k8_prod'
    namespace: 'prometheus'
    command: 'install'
    chartType: 'Name'
    chartName: 'prometheus-community/kube-prometheus-stack'
    releaseName: 'cert-manager'
    valueFile: '$(System.DefaultWorkingDirectory)/helm-chart-values/values.yml'
