grafana:

  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: true

    # grafana.ini:
    #   server:
    #     domain: james-mellors.com
    #     root_url: https://james-mellors.com/grafana
    #     serve_from_sub_path: true
      

    ## Annotations for Grafana Ingress
    ##
    annotations: {
        kubernetes.io/ingress.class: nginx,
        nginx.ingress.kubernetes.io/ssl-redirect: "false",
        nginx.ingress.kubernetes.io/from-to-www-redirect: "true",
        nginx.ingress.kubernetes.io/use-regex: "true",
        cert-manager.io/cluster-issuer: letsencrypt-prod
    }
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    ## Labels to be added to the Ingress
    ##
    labels: {}

    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    # hosts:
    #   - grafana.domain.com
    hosts: 
      - james-mellors.com
      - grafana.james-mellors.com
    

    ## Path for grafana ingress
    path: /

    ## TLS configuration for grafana Ingress
    ## Secret must be manually created in the namespace
    ##
    tls: 
      - secretName: tls-secret
        hosts:
        - grafana.james-mellors.com
    
    # - secretName: grafana-general-tls
    #   hosts:
    #   - grafana.example.com


